- Brightness: 150
- Contrast: 54
- Saturation: 48
- White Balance Temperature, Auto: 0
- Gain: 74
- Sharpness: 76
- Backlight Compensation: 0
- Exposure, Auto: 1
- Exposure (Absolute): 259
- Exposure, Auto Priority: 0
