- Brightness: 113
- Contrast: 42
- Saturation: 84
- White Balance Temperature, Auto: 1
- Gain: 47
#- White Balance Temperature: 4000
- Sharpness: 37
- Backlight Compensation: 1
- Exposure, Auto: 1
- Exposure (Absolute): 707
- Exposure, Auto Priority: 1
