- Brightness: 123
- Contrast: 32
- Saturation: 66
- White Balance Temperature, Auto: 1
- Gain: 15
- Power Line Frequency: 2
- White Balance Temperature: 4000
- Sharpness: 37
- Backlight Compensation: 1
- Exposure, Auto: 1
- Exposure (Absolute): 707
- Exposure, Auto Priority: 1
- Pan (Absolute): 0
- Tilt (Absolute): 0
- Focus: 0
- LED1 Mode: 3
- LED1 Frequency: 0
- Disable video processing: 0
- Raw bits per pixel: 0
