- Brightness: 128
- Contrast: 40
- Saturation: 40
- White Balance Temperature, Auto: 1
- Gain: 50
- Sharpness: 28
- Backlight Compensation: 1
- Exposure, Auto: 1
- Exposure (Absolute): 1153
- Exposure, Auto Priority: 1
