- Brightness: 132
- Contrast: 46
- Saturation: 92
- White Balance Temperature, Auto: 1
- Gain: 12
- Sharpness: 82
- Backlight Compensation: 0
- Exposure, Auto: 1
- Exposure (Absolute): 348
- Exposure, Auto Priority: 1
