- Brightness: 98
- Contrast: 55
- Saturation: 89
- White Balance Temperature, Auto: 1
- Gain: 35
- Sharpness: 49
- Backlight Compensation: 1
- Exposure, Auto: 1
- Exposure (Absolute): 324
- Exposure, Auto Priority: 0
